In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [4]:
data_set=pd.read_csv("agree.csv")
column_means = data_set.mean()
data_set= data_set.fillna(column_means)
data_set.drop('production', inplace=True, axis=1)
data_set.drop('area', inplace=True, axis=1)

In [21]:
le=LabelEncoder()
map={}
le.fit(data_set['state_name'])
map.update(dict(zip(le.classes_,le.transform(le.classes_))))
data_set['state_name']=le.transform(data_set['state_name'])

le.fit(data_set['district_name'])
map.update(dict(zip(le.classes_,le.transform(le.classes_))))
data_set['district_name']=le.transform(data_set['district_name'])

le.fit(data_set['crop_year'])
map.update(dict(zip(le.classes_,le.transform(le.classes_))))
data_set['crop_year']=le.transform(data_set['crop_year'])

le.fit(data_set['season'])
map.update(dict(zip(le.classes_,le.transform(le.classes_))))
data_set['season']=le.transform(data_set['season'])

le.fit(data_set['crop'])
map.update(dict(zip(le.classes_,le.transform(le.classes_))))
crops=le.classes_
data_set['crop']=le.transform(data_set['crop'])

In [40]:
x=data_set.iloc[:,[0,1,2,3,4]].values
y=data_set.iloc[:,[5]].values
y=y.astype('int')  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=10)  

[[  0 427   3   1   2]
 [  0 427   3   1  74]
 [  0 427   3   1  95]
 ...
 [ 32 471  17   4 106]
 [ 32 471  17   5  95]
 [ 32 471  17   5 102]]


In [41]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test) 
from sklearn.svm import SVC   
classifier = SVC(kernel='linear')  
classifier.fit(x_train, np.ravel(y_train))

SVC(kernel='linear')

In [42]:
from sklearn import metrics
y_pred=classifier.predict(x_test)
predictions=metrics.accuracy_score(y_test,y_pred)
print(predictions)

0.42556442306129416


In [45]:
# state_name=map["Andaman and Nicobar Islands"]
# district_name=map["NICOBARS"]
# crop_year=map[2000]
# season=map["Kharif"]
# crop=map["Arecanut"]

# pred=classifier.predict([[state_name,district_name,crop_year,season,crop]])
pred=classifier.predict([[0,0,0,0,0]])
print(pred)

[30]
